### ISSUE TITLE
[Bug Report] Indium conflicts with BetterTrims

### ISSUE THREAD

**Issue by noonbles** [Bawnorton/BetterTrims#23]
Game crashes on Fabulously Optimized modpack 1.20.1

**Steps to Reproduce**
- Step 1: install fabulously optimized 1.20.1 using gdlauncher
- Step 2: install bettertrims
- Step 3: create new world; once it reaches 100% and begins to load chunks, it will crash

Using 1.4.0 of bettertrims
here's the relevant bit of log:

```[17:11:53] [Chunk Render Task Executor #0/ERROR]: Chunk build failed
net.minecraft.class_148: Tessellating block in world - Indium Renderer
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:168) ~[sodium-fabric-mc1.20.1-0.5.2.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:132) ~[sodium-fabric-mc1.20.1-0.5.2.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39) ~[sodium-fabric-mc1.20.1-0.5.2.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) [sodium-fabric-mc1.20.1-0.5.2.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) [sodium-fabric-mc1.20.1-0.5.2.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalAccessError: 'boolean link.infra.indium.renderer.render.TerrainRenderContext.hasTransform()'
	at net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(VanillaModelEncoder.java:54) ~[fabric-renderer-api-v1-3.2.0+39a511ba77-875ed8351b6d5e57.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.FabricBakedModel.emitBlockQuads(FabricBakedModel.java:97) ~[fabric-renderer-api-v1-3.2.0+39a511ba77-875ed8351b6d5e57.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51) ~[fabric-renderer-api-v1-3.2.0+39a511ba77-875ed8351b6d5e57.jar:?]
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitBlockQuads(EmissiveBakedModel.java:64) ~[continuity-3.0.0-beta.3+1.20.1.jar:?]
	at net.minecraft.class_1097.emitBlockQuads(class_1097.java:574) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51) ~[fabric-renderer-api-v1-3.2.0+39a511ba77-875ed8351b6d5e57.jar:?]
	at me.pepperbell.continuity.client.model.CTMBakedModel.emitBlockQuads(CTMBakedModel.java:53) ~[continuity-3.0.0-beta.3+1.20.1.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51) ~[fabric-renderer-api-v1-3.2.0+39a511ba77-875ed8351b6d5e57.jar:?]
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitBlockQuads(EmissiveBakedModel.java:72) ~[continuity-3.0.0-beta.3+1.20.1.jar:?]
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131) ~[indium-1.0.25+mc1.20.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$cog000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543) ~[sodium-fabric-mc1.20.1-0.5.2.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103) ~[sodium-fabric-mc1.20.1-0.5.2.jar:?]
	... 4 more
[17:11:54] [Netty Local Client IO #0/INFO]: Disconnected from server, resetting proxy config values
[17:11:58] [Server thread/INFO]: Unloading level com.seibel.distanthorizons.core.level.DhClientServerLevel@7f28871f
[17:11:58] [Server thread/INFO]: Shutting down ClientRenderState
[17:11:58] [Server thread/INFO]: Shutting down LodRenderer...
[17:11:58] [Server thread/INFO]: Finished shutting down LodRenderer
[17:11:58] [Server thread/INFO]: Shutting down LodQuadTree...
[17:11:58] [Server thread/INFO]: Finished shutting down LodQuadTree
[17:11:58] [Server thread/INFO]: Closing RenderSourceFileHandler with [249] files...
[17:11:58] [Server thread/INFO]: Closing world gen queue
[17:11:58] [Server thread/INFO]: Closing WorldGenerationQueue...
[17:11:58] [Server thread/INFO]: Awaiting world generator thread pool termination...
[17:11:58] [GLProxy-Worker-Thread/INFO]: Renderer Cleanup Started
[17:11:58] [GLProxy-Worker-Thread/INFO]: Renderer Cleanup Complete
[17:12:01] [Server thread/WARN]: World generator thread pool shutdown didn't complete after [3] seconds. Some world generator requests may still be running.
[17:12:01] [Server thread/INFO]: BatchGenerator shutting down...
[17:12:01] [Server thread/INFO]: BatchGenerationEnvironment shutting down...
[17:12:01] [Server thread/INFO]: Canceling in progress generation event futures...
[17:12:01] [Server thread/INFO]: BatchGenerationEnvironment shutdown complete.
[17:12:01] [Server thread/INFO]: Finished closing WorldGenerationQueue
[17:12:01] [Server thread/INFO]: Closed DhClientServerLevel for Wrapped{ServerLevel[New World]@overworld}
[17:12:01] [Server thread/INFO]: Unloading level com.seibel.distanthorizons.core.level.DhClientServerLevel@75551ec1
[17:12:01] [Server thread/INFO]: Closed DhClientServerLevel for Wrapped{ServerLevel[New World]@the_nether}
[17:12:01] [Server thread/INFO]: Unloading level com.seibel.distanthorizons.core.level.DhClientServerLevel@12afd7a
[17:12:01] [Server thread/INFO]: Closed DhClientServerLevel for Wrapped{ServerLevel[New World]@the_end}
[17:12:01] [Server thread/INFO]: closing rrp ebe:base_resources
[17:12:01] [Server thread/INFO]: Closed DhWorld of type Client_Server
[17:12:01] [Server thread/INFO]: Stopping FullDataToRenderDataTransformer
[17:12:01] [Server thread/INFO]: Stopping FullDataFileHandler
[17:12:01] [Server thread/INFO]: Stopping ColumnRenderBufferBuilder
[17:12:01] [Server thread/INFO]: Stopping FullDataFileHandler
[17:12:01] [Server thread/INFO]: Stopping ChunkToLodBuilder
[17:12:01] [Render thread/INFO]: Unloading client level [Wrapped{ClientLevel@overworld}].
[17:12:01] [Render thread/INFO]: Finalizing world map session...
[17:12:01] [Thread-19/INFO]: World map force-cleaned!
[17:12:01] [Render thread/INFO]: World map session finalized.
[17:12:01] [Render thread/INFO]: Stopping worker threads```

**Comment by Bawnorton** [comment]
This is not related to better trims.
